# Generated by Django 3.2.2 on 2021-06-24 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('typeAction', models.TextField(max_length=30)),
                ('numberOne', models.IntegerField()),
                ('numberTwo', models.IntegerField()),
                ('result', models.IntegerField()),
                ('timeSolution', models.IntegerField()),
                ('userResult', models.IntegerField()),
                ('isTrue', models.BooleanField()),
                ('currentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
