# Generated by Django 3.2.2 on 2021-06-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savetask',
            name='isTrue',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='savetask',
            name='timeSolution',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='savetask',
            name='userResult',
            field=models.IntegerField(null=True),
        ),
    ]
